language: java
jdk:
  - oraclejdk7
services: mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('1234') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e 'create database zabavy;'